GET http://localhost:3001/api/network

###

POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "username": "Borel",
  "password": "brl1"
}

###

POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "username": "Yannick",
  "password": "ynnck"
}

###

GET http://localhost:3001/api/sessions/current


###

GET http://localhost:3001/api/segments

###

POST http://localhost:3001/api/games/start

###
GET http://localhost:3001/api/rankings